name: CRD Remote

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v4

    - name: Install XFCE
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies wget

    - name: Configure Desktop
      run: |
        echo xfce4-session > ~/.xsession

    - name: Install Chrome Remote Desktop
      run: |
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt-get install -f -y

    - name: Start CRD
      run: |
        DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="${{ secrets.CRD_CODE }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=runner-github --pin=123456

    - name: Keep Alive
      run: |
        echo "CRD started"
        sleep 21600
