name: Windows 2022 RDP Pinggy

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name fDenyTSConnections -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password
      run: |
        net user runneradmin "Password123!"

    - name: Install OpenSSH client
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

    - name: Start Pinggy Tunnel
      run: |
        ssh -T -p 443 -o StrictHostKeyChecking=no -R0:localhost:3389 tcp@a.pinggy.io

    - name: Keep Alive
      run: |
        for ($i=0; $i -lt 360; $i++) { Start-Sleep -Seconds 60 }
