name: CRD Remote Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Chrome Remote Desktop
      run: |
        Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile crd.msi

    - name: Install Chrome Remote Desktop
      run: |
        Start-Process msiexec.exe -Wait -ArgumentList '/i crd.msi /quiet /norestart'

    - name: Start Chrome Remote Desktop
      run: |
        $path = "${env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        & $path --code="${{ secrets.CRD_CODE }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$env:COMPUTERNAME --pin="123456"

    - name: Keep Alive
      run: |
        Write-Output "CRD Started"
        Start-Sleep -Seconds 21600
